server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/ublog/
      suffix: .jsp
  datasource:   
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    
    # JPA 설정
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      #use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true  